version: '3.8'
services:
  db_clients:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clients_db
    ports:
    - '5435:5432'
    volumes:
    - 'db_clients_data:/var/lib/postgresql/data'

  db_products:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - '5436:5432'
    volumes:
    - 'db_products_data:/var/lib/postgresql/data'
  db_orders:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
    - '5437:5432'
    volumes:
    - 'db_orders_data:/var/lib/postgresql/data'
  sonarqube:
    image: 'sonarqube:lts-community'
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: 'jdbc:postgresql://sonar_db:5432/sonar'
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_conf:/opt/sonarqube/conf'
      - 'sonarqube_data:/opt/sonarqube/data'
      - 'sonarqube_extensions:/opt/sonarqube/extensions'
      - 'sonarqube_logs:/opt/sonarqube/logs'
      - 'sonarqube_temp:/opt/sonarqube/temp'
  sonar_db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - 'sonar_db:/var/lib/postgresql'
      - 'sonar_db_data:/var/lib/postgresql/data'
volumes:
  sonarqube_conf: null
  sonarqube_data: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_temp: null
  sonar_db: null
  sonar_db_data: null
  db_clients_data: null
  db_products_data: null
  db_orders_data: null